### ISSUE TITLE
New Private Window Speed-dial doesn't open

### ISSUE THREAD

**Issue by Acid-Crash** [MatMoul/quickdial-webext#11] opened 2017-10-12 10:36 UTC
When opening New Private Window and then clicking on the New tab Speed-Dial fails to load.
Only FavIcon (in tab) is changed to Extension one but the actual Speed-Dial window remains blank.
Tested on Latest Nightly Win10x64.
FF privacy settings
Clear history when FF/Nightly closes - cache, cookies.
![pwm](https://user-images.githubusercontent.com/32600318/31491976-d7efa576-af51-11e7-9382-7b19e3bd5520.png)

**Comment by scienmind** [comment] 2017-10-12 11:49
Sort-of duplicate of #9

**Comment by Acid-Crash** [comment] 2017-10-12 11:51
Oh sorry didn't see that one. Should I close this one?

**Comment by scienmind** [comment] 2017-10-12 12:04
Thinking about it, probably leave it open.
While both issues do have the same underlying cause, fixing one of then will not necessarily fix it all.

**Comment by MatMoul** [comment] 2017-10-12 18:27
@Acid-Crash Leave this issue open, I will work on it this week-end

**Comment by MatMoul** [comment] 2017-10-14 11:08
Version 0.1.0 published with Private Window support

**Closed by MatMoul** 2017-10-14 11:08 UTC
Labels: bug
